name: GitHub Actions Demo
on:
  push:
    branches: [ "production" ]
  pull_request:
    branches: [ "production" ]
env:
  SSH_SERVER: "0.0.0.127"
  SSH_PORT: "22"
  SSH_USER: "..."
  SSH_PASSWORD: "..."
  SSH_WORKDIR: "/var/..."
  WORKDIR: "/home/runner/work/your-app-name/your-app-name/build"
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 18.x ]
    steps:
      - uses: actions/checkout@v3
      - name: Staring Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: install modules
        run: yarn
      - name: build project
        run: yarn build
      - name: unit test
        run: yarn test:unit
      - name: lint code
        run: yarn lint
      - name: bash
        shell: bash
        run: |
          find $(echo $WORKDIR) -type d | xargs chmod 755
          find $(echo $WORKDIR) -type f | xargs chmod 644
          sshpass -p $(echo $SSH_PASSWORD) scp -o CheckHostIP=no -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -r -P $(echo $SSH_PORT) $(echo $WORKDIR)/. $(echo $SSH_USER)@$(echo $SSH_SERVER):$(echo $SSH_WORKDIR)
          exit
