name: GitHub Actions Demo
on:
  push:
    branches: [ prod ]
  pull_request:
    branches: [ prod ]
jobs:
  init:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 18.x ]
    steps:
      - uses: actions/checkout@v3
      - name: Staring Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: install yarn
        run: npm install --global yarn
      - name: install modules
        run: yarn
      - name: build project
        run: yarn build
      - name: unit test
        run: yarn test:unit
      - name: lint code
        run: yarn lint
