name: Actions Demo
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 18.x ]
    steps:
      - uses: actions/checkout@v3
      - name: Staring Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: install modules
        run: yarn
      - name: build project
        run: yarn build
      - name: unit test
        run: yarn test:unit
      - name: lint code
        run: yarn lint
      - name: bash
        shell: bash
        run: |
          find /home/runner/work/app/app/build -type d | xargs chmod 755
          find /home/runner/work/app/app/build -type f | xargs chmod 644
          sshpass -p kM1hT9tY2w scp -r -P 9999 /home/runner/work/app/app/build/. webspell_test@185.179.190.242:/var/www/webspell/data/www/test2.webspell.ru/www
